[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
]
copyleft = "deny"
default = "deny"

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
