[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016"
]
copyleft = "deny"
default = "deny"
unlicensed = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
allow-git = []
unknown-git = "deny"
unknown-registry = "deny"
