[package]
name = "kafka-connector-derive"
version = "0.1.0"
authors = ["kononnable <kononnable@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true


[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full", "parsing", "visit-mut","derive","extra-traits"] }
